name: flutter_always_on_top_linux
description: A Flutter plugin to keep the window always on top in Linux using C and FFI.
version: 0.1.0
homepage: https://github.com/azddine-01/flutter_always-on-top-linux
environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.10.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1
flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterAlwaysOnTopLinux
